### ISSUE TITLE
Error when spinning up development server

### ISSUE THREAD

**Issue by chkw-rks** [vvvv/vvvv.org#38]
Somehow recently I am not able to start Hugo on my computer...

Back then I can remember it worked properly - since then my setup has not changed.
https://visualprogramming.net/blog/2023/vvvv-beginner-class-winter-2023/

Here is the error log from my console. Any ideas what is going wrong here?

Start building sites … 
hugo v0.111.3-5d4eb5154e1fed125ca8e9b5a0315c4180dab192+extended darwin/amd64 BuildDate=2023-03-12T11:40:50Z VendorInfo=gohugoio
panic: runtime error: index out of range [1] with length 1

goroutine 12 [running]:
github.com/gohugoio/hugo/resources/page.PermalinkExpander.toSliceFunc.func2({0xc0023f8040?, 0x1, 0x30?})
	/root/project/hugo/resources/page/permalinks.go:354 +0xde
github.com/gohugoio/hugo/resources/page.PermalinkExpander.callback.func1({0x102498d80?, 0xc0038ea090?}, {0xc0009b3c10?, 0xc0009b3ba8?})
	/root/project/hugo/resources/page/permalinks.go:57 +0x46
github.com/gohugoio/hugo/resources/page.PermalinkExpander.parse.func1({0x102498d80, 0xc0038ea090})
	/root/project/hugo/resources/page/permalinks.go:158 +0x1a5
github.com/gohugoio/hugo/resources/page.PermalinkExpander.Expand({0xc00027ffb0?, 0xc000314030?, 0xc00027fa10?}, {0xc000d6cae0?, 0x22?}, {0x102498d80, 0xc0038ea090})
	/root/project/hugo/resources/page/permalinks.go:114 +0x5b
github.com/gohugoio/hugo/hugolib.createTargetPathDescriptor(_, {_, _}, _)
	/root/project/hugo/hugolib/page__paths.go:152 +0x5da
github.com/gohugoio/hugo/hugolib.newPagePaths(_, {_, _}, _)
	/root/project/hugo/hugolib/page__paths.go:29 +0x9b
github.com/gohugoio/hugo/hugolib.(*pageMap).newPageFromContentNode.func2({0xc0009b5600, 0x100d19b3a})
	/root/project/hugo/hugolib/content_map_page.go:175 +0x6b
github.com/gohugoio/hugo/lazy.(*Init).Do.func1()
	/root/project/hugo/lazy/init.go:108 +0xe7
github.com/gohugoio/hugo/lazy.(*onceMore).Do(0xc002c079d0?, 0xc000048098?)
	/root/project/hugo/lazy/once.go:53 +0x10d
github.com/gohugoio/hugo/lazy.(*Init).Do(0xc002c12fc0, {0x10246d470?, 0xc000048098?})
	/root/project/hugo/lazy/init.go:89 +0x65
github.com/gohugoio/hugo/lazy.(*Init).Do.func1()
	/root/project/hugo/lazy/init.go:113 +0x1a5
github.com/gohugoio/hugo/lazy.(*onceMore).Do(0xc002c07030?, 0xc000048098?)
	/root/project/hugo/lazy/once.go:53 +0x10d
github.com/gohugoio/hugo/lazy.(*Init).Do(0xc002c12070, {0x10246d470?, 0xc000048098?})
	/root/project/hugo/lazy/init.go:89 +0x65
github.com/gohugoio/hugo/hugolib.(*pageState).initPage(...)
	/root/project/hugo/hugolib/page.go:495
github.com/gohugoio/hugo/hugolib.(*pageState).shiftToOutputFormat(0xc0038ea090, 0x1, 0x0)
	/root/project/hugo/hugolib/page.go:882 +0x49
github.com/gohugoio/hugo/hugolib.(*pageState).initOutputFormat(...)
	/root/project/hugo/hugolib/page.go:486
github.com/gohugoio/hugo/hugolib.(*Site).preparePagesForRender.func1(0xc0009b5a78?)
	/root/project/hugo/hugolib/hugo_sites.go:853 +0x2a
github.com/gohugoio/hugo/hugolib.(*pageMap).withEveryBundlePage.func1({0x1?, 0x0?}, 0xc0006dc330?)
	/root/project/hugo/hugolib/content_map_page.go:691 +0x2a
github.com/gohugoio/hugo/hugolib.contentTrees.Walk.func1({0xc000c1b100?, 0xc0009b5a78?}, {0x101b2fde0?, 0xc001dac1e0?})
	/root/project/hugo/hugolib/content_map.go:876 +0x3b
github.com/armon/go-radix.recursiveWalk(0xc001dac240, 0xc0009b5a78)
	/root/project/gomodcache/github.com/armon/go-radix@v1.0.0/radix.go:519 +0x45
github.com/armon/go-radix.recursiveWalk(0xc0005ed908?, 0xc0009b5a78)
	/root/project/gomodcache/github.com/armon/go-radix@v1.0.0/radix.go:525 +0xa6
github.com/armon/go-radix.recursiveWalk(0x101dc5ac6?, 0xc0009b5a78)
	/root/project/gomodcache/github.com/armon/go-radix@v1.0.0/radix.go:525 +0xa6
github.com/armon/go-radix.recursiveWalk(0x0?, 0xc0009b5a78)
	/root/project/gomodcache/github.com/armon/go-radix@v1.0.0/radix.go:525 +0xa6
github.com/armon/go-radix.recursiveWalk(0xc0005eda88?, 0xc0009b5a78)
	/root/project/gomodcache/github.com/armon/go-radix@v1.0.0/radix.go:525 +0xa6
github.com/armon/go-radix.recursiveWalk(0x3?, 0xc0009b5a78)
	/root/project/gomodcache/github.com/armon/go-radix@v1.0.0/radix.go:525 +0xa6
github.com/armon/go-radix.recursiveWalk(0xc000683040?, 0xc0009b5a78)
	/root/project/gomodcache/github.com/armon/go-radix@v1.0.0/radix.go:525 +0xa6
github.com/armon/go-radix.(*Tree).Walk(...)
	/root/project/gomodcache/github.com/armon/go-radix@v1.0.0/radix.go:447
github.com/gohugoio/hugo/hugolib.contentTrees.Walk({0xc000709ae0, 0x4, 0xd0?}, 0xc0009b5ab8)
	/root/project/hugo/hugolib/content_map.go:874 +0x5b
github.com/gohugoio/hugo/hugolib.(*pageMap).withEveryBundlePage(0xc000504000?, 0xc0028ac820?)
	/root/project/hugo/hugolib/content_map_page.go:689 +0x47
github.com/gohugoio/hugo/hugolib.(*Site).preparePagesForRender(0x10354cd30?, 0x40?, 0xc000048098?)
	/root/project/hugo/hugolib/hugo_sites.go:852 +0x5e
github.com/gohugoio/hugo/hugolib.(*HugoSites).render(0xc000000b40, 0xc00070bea0)
	/root/project/hugo/hugolib/hugo_sites_build.go:307 +0x566
github.com/gohugoio/hugo/hugolib.(*HugoSites).Build.func4()
	/root/project/hugo/hugolib/hugo_sites_build.go:146 +0x2a
runtime/trace.WithRegion({0x10246d4e0?, 0xc000b5a7e0?}, {0x101dd14cb, 0x6}, 0xc0005ede58)
	/usr/local/go/src/runtime/trace/annotation.go:141 +0xe3
github.com/gohugoio/hugo/hugolib.(*HugoSites).Build(0xc000000b40, {0x0, {0x0, 0x0}, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
	/root/project/hugo/hugolib/hugo_sites_build.go:148 +0x5f3
github.com/gohugoio/hugo/commands.(*commandeer).buildSites(...)
	/root/project/hugo/commands/hugo.go:738
github.com/gohugoio/hugo/commands.(*commandeer).fullBuild.func3()
	/root/project/hugo/commands/hugo.go:313 +0x88
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/root/project/gomodcache/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/root/project/gomodcache/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5

**Comment by joreg** [comment]
please update your hugo version, we're always building against latest.

**Comment by chkw-rks** [comment]
Yes, works when updating via Homebrew.
